POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvbyIsImlkIjoiNjI1ZDdkNzcyY2VjM2I4MjhlNmU2ZjMwIiwiaWF0IjoxNjUwMzQ4ODkzfQ.rrXLEmTO3PaS-gNl4ynlD6peOOLo5QRXYNZfMqAR-9k

{
    "title": "Uuden blogin lisäys tokenilla",
    "author": "Foo",
    "url": "foo.bar",
    "likes": 3
}